import React from 'react';

const realmOptions = [
    "Ravencrest",
    "Ragnaros",
    "Aerie Peak",
    "Aggramar",
    "Alonsus",
    "Anachronos",
    "Arathor",
    "Aszune",
    "Azjol-Nerub",
    "Azuremyst",
    "Blade's Edge",
    "Bloodhoof",
    "Bronzebeard",
    "Bronze Dragonflight",
    "Chamber of Aspects",
    "Darkspear",
    "Doomhammer",
    "Draenor",
    "Dragonblight",
    "Emerald Dream",
    "Eonar",
    "Ghostlands",
    "Hellfire",
    "Hellscream",
    "Khadgar",
    "Kilrogg",
    "Kul Tiras",
    "Lightbringer",
    "Nagrand",
    "Nordrassil",
    "Quel'Thalas",
    "Runetotem",
    "Saurfang",
    "Shadowsong",
    "Silvermoon",
    "Stormrage",
    "Terenas",
    "Terokkar",
    "Thunderhorn",
    "Turalyon",
    "Vek'nilash",
    "Wildhammer",
    "PvP Servers, English",
    "Agamaggan",
    "Aggra(Português)",
    "Al'Akir",
    "Ahn'Qiraj",
    "Auchindoun",
    "Balnazzar",
    "Bladefist",
    "Bloodfeather",
    "Bloodscalp",
    "Boulderfist",
    "Burning Blade",
    "Burning Legion",
    "Burning Steppes",
    "Chromaggus",
    "Crushridge",
    "Daggerspine",
    "Darksorrow",
    "Deathwing",
    "Dentarg",
    "Dragonmaw",
    "Drak'thul",
    "Dunemaul",
    "Emeriss",
    "Executus",
    "Frostmane",
    "Frostwhisper",
    "Genjuros",
    "Grim Batol",
    "Haomarush",
    "Hakkar",
    "Jaedenar",
    "Karazhan",
    "Kazzak",
    "Kor'gall",
    "Laughing Skull",
    "Lightning's Blade",
    "Magtheridon",
    "Mazrigos",
    "Molten Core",
    "Neptulon",
    "Outland",
    "Shadowmoon",
    "Shattered Halls",
    "Shattered Hand",
    "Skullcrusher",
    "Spinebreaker",
    "Stonemaul",
    "Stormreaver",
    "Stormscale",
    "Sunstrider",
    "Sylvanas",
    "Talnivarr",
    "Tarren Mill",
    "The Maelstrom",
    "Trollbane",
    "Twilight's Hammer",
    "Twisting Nether",
    "Vashj",
    "Warsong",
    "Xavius",
    "Zenedar",
    "Argent Dawn",
    "Darkmoon Faire",
    "Earthen Ring",
    "Moonglade",
    "Steamwheedle Cartel",
    "The Sha'tar",
    "Defias Brotherhood",
    "Ravenholdt",
    "Scarshield Legion",
    "Sporeggar",
    "The Venture Co EU",
];

const jsx = [];

realmOptions.forEach(realm => {
    jsx.push((
        <option name={realm.toLowerCase()}>{realm}</option>
    ));
});

export const RealmOptions = () => {
    return jsx;
}